# Site settings
title: explog
email: yati.sagade@gmail.com
description: "Explore."
baseurl: ""
url: "http://yati-sagade.github.io"
twitter_username: yati_itay
github_username: yati-sagade

# Build settings
markdown: kramdown
permalink: pretty
